# Generated by Django 4.1.1 on 2022-10-19 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation_ac',
            name='created_at',
        ),
        migrations.AddField(
            model_name='operation_ac',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 0, 31, 24, 115192, tzinfo=datetime.timezone.utc)),
        ),
    ]
