# Generated by Django 4.1.1 on 2022-09-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_operation_ac_created_at_alter_account_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.CharField(default='mercadoPago', max_length=70),
            preserve_default=False,
        ),
    ]
