# Generated by Django 4.1.1 on 2022-10-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation_ac',
            old_name='decription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='operation_ac',
            name='category',
            field=models.CharField(default='', max_length=70),
        ),
    ]
