# Generated by Django 3.2.16 on 2022-10-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_decription_operation_ac_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_ac',
            name='transfer_id',
            field=models.IntegerField(default=0),
        ),
    ]
