# Generated by Django 4.1.1 on 2022-10-10 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_operation_ac_transfer_id_alter_operation_ac_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_ac',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.category'),
        ),
    ]
