# Generated by Django 3.2.16 on 2022-10-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_ac',
            name='category',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
    ]
