# Generated by Django 4.1.1 on 2022-10-13 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_operation_ac_category'),
        ('accounts', '0007_alter_operation_ac_category'),
    ]

    operations = [
    ]
