# Generated by Django 3.2.16 on 2022-10-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_operation_ac_category'),
        ('accounts', '0007_alter_operation_ac_category'),
    ]

    operations = [
    ]
